CodeFirstKisiler/Controllers/AdresController.cs
using CodeFirstKisiler.Models;
using CodeFirstKisiler.Models.Manager;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CodeFirstKisiler.Controllers
{
    public class AdresController : Controller
    {
        DatabaseContext db = new DatabaseContext();
        // GET: Adres
        public ActionResult Yeni()
        {//ısmı secıyor ıdsı gelıyro=dropdownlıst mantıgı
            List<SelectListItem> kisilerlist = db.Kisiler.Select(x => new SelectListItem { Text = x.Ad, Value = x.ID.ToString() }).ToList();
            TempData["Kisiler"] = kisilerlist;//yönlendrıme gırsede verıler kaybolmuyor 
            ViewBag.kisiler = kisilerlist;
            return View();
        }
        [HttpPost]
        public ActionResult Yeni(Adres adres)
        {
            Kisiler kisi = db.Kisiler.Where(x => x.ID == adres.KisiId).FirstOrDefault();
            if (kisi != null)
            {
                adres.Kisiler = kisi;
                db.Adresler.Add(adres);
                int sonuc = db.SaveChanges();
                if (sonuc > 0)
                {
                    ViewBag.Result = "Adres başarıyla eklenmiştir";
                    ViewBag.Status = "Success";
                }
                else
                {

                    ViewBag.Result = "Adres başarıyla eklenmemiştir";
                    ViewBag.Status = "danger";
                }
                ViewBag.kisiler = TempData["Kisiler"];

            }
            return View();

        }
        public ActionResult Duzenle(int? adresid)
        {
            Adres adres = new Adres();
            if (adresid != null)
            {
                List<SelectListItem> kisilerlist = db.Kisiler.Select(x => new SelectListItem()
                {
                    Text=x.Ad,
                    Value=x.ID.ToString()


                }).ToList();
                TempData["Kisiler"] = kisilerlist;
                ViewBag.kisiler = kisilerlist;
                adres = db.Adresler.Where(x => x.ID == adresid).FirstOrDefault();
            }
            return View(adres);


        }
        [HttpPost]
        public ActionResult Duzenle(Adres adress, int? adresid)
        {
            Kisiler kisi = db.Kisiler.Where(x => x.ID == adress.KisiId).FirstOrDefault();
            Adres adres = db.Adresler.Where(x => x.ID == adresid).FirstOrDefault();
            if (kisi != null)
            {
                adres.Kisiler = kisi;
                adres.AdresTanim = adress.AdresTanim;
             
                int sonuc = db.SaveChanges();
                if (sonuc > 0)
                {
                    ViewBag.Result = "Adres başarıyla güncellenmiştir";
                    ViewBag.Status = "success";
                }
                else
                {
                    ViewBag.Result = "Adres Başarıyla güncellenmemiştir";
                    ViewBag.Status = "danger";
                }
                ViewBag.kisiler = TempData["Kisiler"];
            }
            return View();
        }

        public ActionResult Sil(int? adresid)
        {
            Adres adresx = new Adres();
            if (adresid != null)
            {
                adresx = db.Adresler.Where(x => x.ID == adresid).FirstOrDefault();
                adresx.Kisiler = db.Kisiler.Where(x => x.ID == adresx.KisiId).FirstOrDefault();
            }
            return View(adresx);

        }
        [HttpPost]
        public ActionResult SilOk(int? adresid)
        {
            Adres adresx = new Adres();
            if (adresid != null)
            {
                adresx = db.Adresler.Where(x => x.ID == adresid).FirstOrDefault();
                adresx.Kisiler = db.Kisiler.Where(x => x.ID == adresx.KisiId).FirstOrDefault();
                db.Adresler.Remove(adresx);
                db.SaveChanges();
            }
            return RedirectToAction("Index", "Home");


        }



    }
}

CodeFirstKisiler/Controllers/HomeController.cs
using CodeFirstKisiler.Models;
using CodeFirstKisiler.Models.Manager;
using CodeFirstKisiler.Models.ViewsModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CodeFirstKisiler.Controllers
{
    public class HomeController : Controller
    {
        DatabaseContext db = new DatabaseContext();
        // GET: Home
        public ActionResult Index()
        {
            HomePageViewsModel model = new HomePageViewsModel();
            model.Kisiler = db.Kisiler.ToList();
            model.Adresler = db.Adresler.ToList();
            return View(model);
        }

    }
}

CodeFirstKisiler/Controllers/KisiController.cs
using CodeFirstKisiler.Filters;
using CodeFirstKisiler.Models;
using CodeFirstKisiler.Models.Manager;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CodeFirstKisiler.Controllers
{
    public class KisiController : Controller
    {
        DatabaseContext db = new DatabaseContext();
        // GET: Kisi
        public ActionResult Yeni()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Yeni(Kisiler kisi)
        {
            db.Kisiler.Add(kisi);
            int sonuc = db.SaveChanges();
            if (sonuc > 0)
            {
                ViewBag.Result = "Kişi başarıyla eklendi";
                ViewBag.Status = "success";

            }
            else
            {
                ViewBag.Result = "Kişi eklenememiştir";
                ViewBag.Status = "danger";
            }
            return View();

        }
        [AutFilter]
        public ActionResult Duzenle(int? kisiid)
        {
            Kisiler kisi = new Kisiler();
            if (kisiid != null)
            {
                kisi = db.Kisiler.Where(x => x.ID == kisiid).FirstOrDefault();
            }
            return View(kisi);
        }
        [HttpPost]
        public ActionResult Duzenle(Kisiler model, int? kisiid)
        {
            Kisiler kisi = db.Kisiler.Where(x => x.ID == kisiid).FirstOrDefault();
            if (kisi != null)
            {
                kisi.Ad = model.Ad;
                kisi.Soyad = model.Soyad;
                kisi.Yas = model.Yas;
              int sonuc=  db.SaveChanges();
                if (sonuc > 0)
                {
                    ViewBag.Result = "Kişi güncellenmiştir";//mesajı tasıyorum
                    ViewBag.Status = "success";
                }
                else
                {
                    ViewBag.Result = "Kişi güncellenmemiştir";//mesajı tasıyorum
                    ViewBag.Status = "danger";
                }

            }
            return View();

        }
        public ActionResult Sil(int? kisiid)
        {
            Kisiler kisi = new Kisiler();
            if (kisiid != null)
            {
                kisi = db.Kisiler.Where(x => x.ID == kisiid).FirstOrDefault();
              
            }
            return View(kisi);
        }
        [HttpPost,ActionName("Sil")]
        public ActionResult SilOk(int? kisiid)
        {
            Kisiler kisi = new Kisiler();
            if (kisiid != null)
            {
                kisi = db.Kisiler.Where(x => x.ID == kisiid).FirstOrDefault();
                db.Kisiler.Remove(kisi);
                db.SaveChanges();
            }
            return RedirectToAction("Index", "Home");
        }
       

        
    }
}

CodeFirstKisiler/Views/Home/Index.cshtml
@model CodeFirstKisiler.Models.ViewsModel.HomePageViewsModel
@{
    ViewBag.Title = "Index";
}

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <h2>Ana Sayfa</h2>
            <hr />
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div>
                @Html.ActionLink("Yeni Kişi", "Yeni", "Kisi",null, new { @class = "btn btn-success" })

            </div>
            <br />
            <ul class="list-group">
                <li class="list-group-item active"> Kişiler</li>
                @foreach (var item in Model.Kisiler)
                {
            <li class="list-group-item">
                @Html.ActionLink("Düzenle", "Duzenle", "Kisi", new { kisiid = item.ID }, new { @class = "btn btn-warning" })

                @Html.ActionLink("Sil", "Sil", "Kisi", new { kisiid = item.ID }, new { @class = "btn btn-danger" })
                <i class="far fa-user red"></i>
                @(item.Ad+" "+item.Soyad)  (@item.Yas)

            </li>

                }

            </ul>




        </div>
        <div class="col-md-6">
            <div>
                @Html.ActionLink("Yeni Adres", "Yeni", "Adres", null, new { @class = "btn btn-success" })
            </div>
            <br />
            <ul class="list-group">
                <li class="list-group-item active">Adresler</li>

                @foreach (var item in Model.Adresler)
                {
            <li class="list-group-item">

                @Html.ActionLink("Düzenle", "Duzenle", "Adres", new { adresid = item.ID }, new { @class = "btn btn-warning" })

                @Html.ActionLink("Sil", "Sil", "Adres", new {adresid= item.ID }, new { @class = "btn btn-danger" })
                <i class="far fa-user red"></i>
               

                <i class="fas fa-home red"></i>
                @item.AdresTanim (<i>@(item.Kisiler.Ad +" "+item.Kisiler.Soyad)</i>)
            </li>
                }

            </ul>



        </div>
    </div>




</div>